correcting server login

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,14 +1,27 @@
 #!/usr/bin/env bash
 # Bash script that transfers a file from our client to a server
 
-if [ $# -lt 3 ];
+if [ $# -lt 4 ];
 then
     echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
-    exit;
+    exit 1;
 fi;
-if [ $# -ge 4 ];
+
+#assign params to variables
+
+path_to_file=$1;
+ip=$2;
+username=$3;
+path_to_ssh_key=$4;
+
+#disabling strict host key checking
+    scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+#checking if transfer was success
+
+if [$? -eq 0]
 then
-    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
+	echo "Transfer was succesful"
 else
-    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
+	echo "Transfer failed!"
 fi;
